name: New Deploy All .NET Core AppServices for Keneils Project

on: [push]

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  CLASS_DIRECTORY: ./ClassAPI
  CLASS_AZURE_WEBAPP_PACKAGE_PATH: ./ClassAPI/published
  CLAN_DIRECTORY: ./ClanAPI
  CLAN_AZURE_WEBAPP_PACKAGE_PATH: ./ClanAPI/published
  FACEOFF_DIRECTORY: ./FaceOffAPI
  FACEOFF_AZURE_WEBAPP_PACKAGE_PATH: ./FaceOffAPI/published
  FE_DIRECTORY: ./AnimeBattleFrontEnd
  FE_AZURE_WEBAPP_PACKAGE_PATH: ./AnimeBattleFrontEnd/published
  
jobs:
  
  #build:
  build-class-service:
    name: Build Class Service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    
    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build --configuration Release --no-restore

   # - name: Test app
   #   run: dotnet test --no-build

    - name: Publish app for deploy
      run: dotnet publish --configuration Release --no-build --output ${{ env.CLASS_AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: animeclassapi
        publish-profile: ${{ secrets.CLASS_PP }}
        package: ${{ env.CLASS_AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.CLASS_AZURE_WEBAPP_PACKAGE_PATH }}
