name: Deploy FrontEnd AppService for Keneils Project

on: 
  push:
    branches:
    - master

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  FE_DIRECTORY: AnimeBattleFrontEnd
  FE_AZURE_WEBAPP_PACKAGE_PATH: ./AnimeBattleFrontEnd/published
  
jobs:
  
  #build:
  build-frontend-service:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.FE_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.FE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.FE_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.FE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.FE_AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: animebattlefrontend 
        publish-profile: ${{ secrets.FRONTEND_PP }}
        package: ${{ env.FE_AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.FE_AZURE_WEBAPP_PACKAGE_PATH }}
